![purple-divider](https://user-images.githubusercontent.com/7065401/52071927-c1cd7100-2562-11e9-908a-dde91ba14e59.png)


# What is a return?

The return formula


$$ R_{(t+1, t)} = \frac{  P_{t+1} - P_t }{  P_{t}   } $$

Or alternatively:

$$ R_{(t+1, t)} = \frac{  P_{t+1}  }{  P_t  }  - 1 $$

In [4]:
import numpy as np
import pandas as pd


In [10]:
prices_a = [8.70, 8.91, 8.71]
prices = np.array(prices_a)
print(prices)

[8.7  8.91 8.71]


In [15]:
print(prices[1:]/prices[:-1])
print(prices[1:]/prices[:-1] - 1)

[1.02413793 0.97755331]
[ 0.02413793 -0.02244669]


In [16]:
prices = pd.DataFrame(prices_a)
print(prices)

      0
0  8.70
1  8.91
2  8.71


In [18]:
prices = pd.DataFrame({'BLUE':[8.70, 8.91, 8.81, 8.43, 8.73] , 
                      'ORANGE':[10.66, 11.08, 10.71, 11.59, 12.11]    
                      })
print(prices)

   BLUE  ORANGE
0  8.70   10.66
1  8.91   11.08
2  8.81   10.71
3  8.43   11.59
4  8.73   12.11


In [19]:
print(prices.iloc[1:]/prices.iloc[:-1])

   BLUE  ORANGE
0   NaN     NaN
1   1.0     1.0
2   1.0     1.0
3   1.0     1.0
4   NaN     NaN


In [27]:
print(prices.iloc[1:].values/prices.iloc[:-1].values)

print()

print(prices.iloc[1:].values/prices.iloc[:-1].values -1)

#print(prices.iloc[1:].values/prices.iloc[:-1].values)


[[1.02413793 1.03939962]
 [0.98877666 0.9666065 ]
 [0.9568672  1.0821662 ]
 [1.03558719 1.04486626]]

[[ 0.02413793  0.03939962]
 [-0.01122334 -0.0333935 ]
 [-0.0431328   0.0821662 ]
 [ 0.03558719  0.04486626]]


In [25]:
prices/prices.shift(1)

BLUE    ORANGE
0       NaN       NaN
1  1.024138  1.039400
2  0.988777  0.966606
3  0.956867  1.082166
4  1.035587  1.044866

In [28]:
prices/prices.shift(1) - 1

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.011223 -0.033394
3 -0.043133  0.082166
4  0.035587  0.044866

In [29]:
prices.pct_change()

BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.011223 -0.033394
3 -0.043133  0.082166
4  0.035587  0.044866

In [31]:
# To summarize.

# Can get percentage change in three ways:

print(prices.iloc[1:].values/prices.iloc[:-1].values)
print(prices/prices.shift()) # default value of shift() is 1
print(prices.pct_change())


[[1.02413793 1.03939962]
 [0.98877666 0.9666065 ]
 [0.9568672  1.0821662 ]
 [1.03558719 1.04486626]]
       BLUE    ORANGE
0       NaN       NaN
1  1.024138  1.039400
2  0.988777  0.966606
3  0.956867  1.082166
4  1.035587  1.044866
       BLUE    ORANGE
0       NaN       NaN
1  0.024138  0.039400
2 -0.011223 -0.033394
3 -0.043133  0.082166
4  0.035587  0.044866
